version: '3'
services:
  locker-redis:
    image: "redis:latest"
    ports:
      - "26379:6379"
    volumes:
      - "./data/meta-redis:/data"
  meta-redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/meta-redis:/data"
  tracker-redis:
    image: "redis:latest"
    ports:
      - "16379:6379"
    volumes:
      - "./data/tracker-redis:/data"
      
