// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/metadata/api/proto/register.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a005ebff46399b, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a005ebff46399b, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type GetMemberRequest struct {
	PeerIds              []string `protobuf:"bytes,1,rep,name=peer_ids,json=peerIds,proto3" json:"peer_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberRequest) Reset()         { *m = GetMemberRequest{} }
func (m *GetMemberRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemberRequest) ProtoMessage()    {}
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a005ebff46399b, []int{2}
}

func (m *GetMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberRequest.Unmarshal(m, b)
}
func (m *GetMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberRequest.Marshal(b, m, deterministic)
}
func (m *GetMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberRequest.Merge(m, src)
}
func (m *GetMemberRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemberRequest.Size(m)
}
func (m *GetMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberRequest proto.InternalMessageInfo

func (m *GetMemberRequest) GetPeerIds() []string {
	if m != nil {
		return m.PeerIds
	}
	return nil
}

type GetMemberResponse struct {
	Members              []*MetadataMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetMemberResponse) Reset()         { *m = GetMemberResponse{} }
func (m *GetMemberResponse) String() string { return proto.CompactTextString(m) }
func (*GetMemberResponse) ProtoMessage()    {}
func (*GetMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a005ebff46399b, []int{3}
}

func (m *GetMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberResponse.Unmarshal(m, b)
}
func (m *GetMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberResponse.Marshal(b, m, deterministic)
}
func (m *GetMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberResponse.Merge(m, src)
}
func (m *GetMemberResponse) XXX_Size() int {
	return xxx_messageInfo_GetMemberResponse.Size(m)
}
func (m *GetMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberResponse proto.InternalMessageInfo

func (m *GetMemberResponse) GetMembers() []*MetadataMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type MetadataMember struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataMember) Reset()         { *m = MetadataMember{} }
func (m *MetadataMember) String() string { return proto.CompactTextString(m) }
func (*MetadataMember) ProtoMessage()    {}
func (*MetadataMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a005ebff46399b, []int{4}
}

func (m *MetadataMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataMember.Unmarshal(m, b)
}
func (m *MetadataMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataMember.Marshal(b, m, deterministic)
}
func (m *MetadataMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataMember.Merge(m, src)
}
func (m *MetadataMember) XXX_Size() int {
	return xxx_messageInfo_MetadataMember.Size(m)
}
func (m *MetadataMember) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataMember.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataMember proto.InternalMessageInfo

func (m *MetadataMember) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *MetadataMember) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type DeleteRequest struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a005ebff46399b, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a005ebff46399b, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "proto.RegisterResponse")
	proto.RegisterType((*GetMemberRequest)(nil), "proto.GetMemberRequest")
	proto.RegisterType((*GetMemberResponse)(nil), "proto.GetMemberResponse")
	proto.RegisterType((*MetadataMember)(nil), "proto.MetadataMember")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
}

func init() {
	proto.RegisterFile("pkg/metadata/api/proto/register.proto", fileDescriptor_c9a005ebff46399b)
}

var fileDescriptor_c9a005ebff46399b = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x51, 0xf3, 0x31, 0x62, 0x8c, 0x83, 0xb5, 0x31, 0xa7, 0xb2, 0x20, 0xe4, 0x62, 0x03,
	0x15, 0xf1, 0x54, 0xf0, 0x50, 0x10, 0x0f, 0xbd, 0xe4, 0x0f, 0x48, 0xca, 0x0e, 0x25, 0x68, 0x4c,
	0xdc, 0x5d, 0xff, 0xa1, 0x3f, 0x4c, 0xdc, 0x8f, 0xd6, 0xa6, 0xf6, 0xb4, 0x3b, 0x6f, 0xde, 0xcc,
	0xbc, 0xf7, 0xe0, 0xb6, 0x7f, 0x5b, 0x97, 0x2d, 0xa9, 0x9a, 0xd7, 0xaa, 0x2e, 0xeb, 0xbe, 0x29,
	0x7b, 0xd1, 0xa9, 0xae, 0x14, 0xb4, 0x6e, 0xa4, 0x22, 0x31, 0xd5, 0x25, 0x9e, 0xea, 0x87, 0x3d,
	0xc0, 0x45, 0x65, 0x1b, 0x15, 0x7d, 0x7e, 0x91, 0x54, 0x98, 0x80, 0xdf, 0xf0, 0xcc, 0x9b, 0x78,
	0x45, 0x5c, 0xf9, 0x0d, 0x47, 0x84, 0x93, 0x9a, 0x73, 0x91, 0xf9, 0x1a, 0xd1, 0x7f, 0x86, 0x90,
	0x6e, 0xc7, 0x64, 0xdf, 0x7d, 0x48, 0x62, 0x77, 0x90, 0x3e, 0x93, 0x5a, 0x52, 0xbb, 0xda, 0xee,
	0xba, 0x81, 0xa8, 0x27, 0x12, 0xaf, 0x0d, 0x97, 0x99, 0x37, 0x39, 0x2e, 0xe2, 0x2a, 0xfc, 0xad,
	0x5f, 0xb8, 0x64, 0x0b, 0xb8, 0xfc, 0x43, 0x37, 0x3b, 0xb0, 0x84, 0xb0, 0xd5, 0x88, 0xa1, 0x9f,
	0xcd, 0x46, 0x46, 0xee, 0x74, 0x69, 0x0d, 0x59, 0xbe, 0x63, 0xb1, 0x39, 0x24, 0xbb, 0x2d, 0x1c,
	0x43, 0x68, 0x4f, 0x5a, 0x0f, 0x81, 0xb9, 0xf8, 0xaf, 0x8f, 0x02, 0xce, 0x17, 0xf4, 0x4e, 0x8a,
	0x9c, 0xe0, 0x43, 0xd3, 0x2c, 0x85, 0xc4, 0x31, 0x8d, 0xd6, 0xd9, 0xb7, 0x07, 0x91, 0xbb, 0x8d,
	0x73, 0x88, 0x5c, 0x20, 0x78, 0x6d, 0x35, 0x0f, 0x82, 0xcd, 0xc7, 0x7b, 0xb8, 0x4d, 0xee, 0x08,
	0x9f, 0x20, 0xde, 0x84, 0x81, 0x8e, 0x37, 0x4c, 0x33, 0xcf, 0xf6, 0x1b, 0x9b, 0x0d, 0x8f, 0x10,
	0x18, 0x7d, 0x78, 0x65, 0x59, 0x3b, 0xc6, 0xf2, 0xd1, 0x00, 0x75, 0x83, 0xab, 0x40, 0xe3, 0xf7,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x48, 0xcf, 0xeb, 0x7e, 0x38, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetadataClient is the client API for Metadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type metadataClient struct {
	cc *grpc.ClientConn
}

func NewMetadataClient(cc *grpc.ClientConn) MetadataClient {
	return &metadataClient{cc}
}

func (c *metadataClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.Metadata/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataClient) GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error) {
	out := new(GetMemberResponse)
	err := c.cc.Invoke(ctx, "/proto.Metadata/GetMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.Metadata/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServer is the server API for Metadata service.
type MetadataServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetMember(context.Context, *GetMemberRequest) (*GetMemberResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterMetadataServer(s *grpc.Server, srv MetadataServer) {
	s.RegisterService(&_Metadata_serviceDesc, srv)
}

func _Metadata_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Metadata/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metadata_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Metadata/GetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServer).GetMember(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metadata_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Metadata/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metadata_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Metadata",
	HandlerType: (*MetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Metadata_Register_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _Metadata_GetMember_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Metadata_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/metadata/api/proto/register.proto",
}
